
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import TopFilterBar from "./components/TopFilterBar/TopFilterBar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
    <body className='h-full font-sans antialiased flex'>
        <Sidebar />
         <div className="flex-1 flex flex-col">
          <TopFilterBar />
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
